### ISSUE TITLE
.interp_quick() - Error in output when asked to interpolate above param range

### ISSUE THREAD

**Issue by kateharborne** [asgr/ProSpect#7]
https://github.com/asgr/ProSpect/blob/d340c64555ba631257513ea4c99b0069cdebf477/R/utility.R#L23

Currently, if the requested `x` is **below** the range given by `params`, the function will return the index of the first parameter for both `ID_lo` and `ID_hi`.

However, when the requested `x` is **above** the range give by `params`, the function returns the _value_ at the final parameter rather than the index for `ID_lo` and `ID_hi`. 

Current code:
```
  if(x > max(params)){
    return(c(max(params), max(params),0,1))
  }
```
Suggested change:
```
  if(x > max(params)){
    return(c(length(params), length(params),0,1))
  }
```

**Comment by asgr** [comment]
Thanks- in now!
